# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XVqauQqy3FQDN_nYrOdiXgBuAYWa4GR2
"""

import math
import pandas as pd
from sympy import symbols
from sympy import pprint, matrix_multiply_elementwise
from sympy import sin,cos,eye
from sympy.matrices import Matrix

a, alpha, d, theta, pi = symbols("ai alphai di thetai pi")

def generateDHParameters(theta1, theta2, theta3, theta4, theta5, theta6, theta7, d1, d3, d5, d7, a3):
    paramsDH = {"alpha":[math.pi/2, -math.pi/2, -math.pi/2, math.pi/2, math.pi/2, -math.pi/2, 0],
            "a":[0, 0, a3, -a3, 0, a3, 0],
            "d":[d1, 0, d3, 0, d5, 0, -d7],
            "theta":[theta1, theta2, theta3, theta4, theta5, theta6, theta7]
    }
    paramsDH_df = pd.DataFrame(data = paramsDH)

    # Display the DH Parameters
    return paramsDH_df

def FrankaEmikaPandaDH(theta1, theta2, theta3, theta4, theta5, theta6, theta7):
    T_display = Matrix([
        [cos(theta),-sin(theta) * cos(alpha), sin(theta)* sin(alpha), a * cos(theta)],
        [sin(theta), cos(theta) * cos(alpha), -cos(theta) * sin(alpha), a * sin(theta)],
        [0, sin(alpha), cos(alpha), d],
        [0, 0, 0, 1]
    ])

    # The Transformation Matrix
    pprint(T_display)
    print('\n')

    # DH Parameters of Franka Emika panda cobot:
    paramsDH_FE = generateDHParameters(theta1, theta2, theta3, theta4, theta5, theta6, theta7, 0.3330, 0.3160, 0.3840, 0.1070, 0.0880)
    T_ = eye(4)

    for index, rows in paramsDH_FE.iterrows():
        alpha_ = rows['alpha']
        a_ = rows['a']
        d_ = rows['d']
        theta_ = rows['theta']
        T = Matrix([
            [math.cos(theta_),-math.sin(theta_) * math.cos(alpha_), math.sin(theta_)* math.sin(alpha_), a_ * math.cos(theta_)],
            [math.sin(theta_), math.cos(theta_) * math.cos(alpha_), -math.cos(theta_) * math.sin(alpha_), a_ * math.sin(theta_)],
            [0, math.sin(alpha_), math.cos(alpha_), d_],
            [0, 0, 0, 1]
        ])
        print("Transformation from Frame ",index ," to Frame ",index +1,"\n")
        print("\n")
        pprint(T)
        print("\n")
        T_ = T_ * T

    print("Final Transformation Matrix")
    print("\n")  
    pprint(T_)
    print("\n")

# 5 configurations

# Uncomment the 5 different iterations to get the results

print("Please consider all the extreme values to be zero as they are multiplied with e^-16,17,32 etc.")
print("\n")
print("First configuration")
print("\n")
FrankaEmikaPandaDH(0, 0, 0, 0, 0, 0, 0)
print("\n")
# print("second configuration")
# print("\n")
# FrankaEmikaPandaDH(math.pi/2, 0, 0, 0, 0, 0, 0)
# print("\n")
# print("Third configuration")
# print("\n")
# FrankaEmikaPandaDH(0, 0, math.pi/2, 0, 0, 0, 0)
# print("\n")
# print("Fourth configuration")
# print("\n")
# FrankaEmikaPandaDH(0, 0, 0, math.pi/2, 0, 0, 0)
# print("\n")
# print("Fifth configuration")
# print("\n")
# FrankaEmikaPandaDH(0, 0, 0, 0, 0, math.pi/2, 0)